services:
  cmdi-server:
    build:
      context: .
    container_name: cmdi-server
    restart: unless-stopped
    volumes:
      - "./app.py:/app/app.py"
      - "./tmp:/app/tmp"
      - "./templates:/app/templates"
      - "./styles:/app/styles"
    ports:
      - "8000:8000"
